/* 
 * WeatherForecast
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CameraApiTests
    {
        private CameraApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CameraApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CameraApi
            //Assert.IsInstanceOfType(typeof(CameraApi), instance, "instance is a CameraApi");
        }

        /// <summary>
        /// Test ApiCameraGet
        /// </summary>
        [Test]
        public void ApiCameraGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiCameraGet();
            
        }
        /// <summary>
        /// Test ApiCameraStreamingGet
        /// </summary>
        [Test]
        public void ApiCameraStreamingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.ApiCameraStreamingGet(id);
            
        }
        /// <summary>
        /// Test ApiCameraVideosGet
        /// </summary>
        [Test]
        public void ApiCameraVideosGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiCameraVideosGet();
            
        }
    }

}
