/* 
 * WeatherForecast
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HistoryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class HistoryApiTests
    {
        private HistoryApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new HistoryApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HistoryApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' HistoryApi
            //Assert.IsInstanceOfType(typeof(HistoryApi), instance, "instance is a HistoryApi");
        }

        /// <summary>
        /// Test ApiHistoryGet
        /// </summary>
        [Test]
        public void ApiHistoryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiHistoryGet();
            
        }
        /// <summary>
        /// Test ApiHistoryPost
        /// </summary>
        [Test]
        public void ApiHistoryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HistoryRequest body = null;
            //instance.ApiHistoryPost(body);
            
        }
    }

}
