/* 
 * WeatherForecast
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MemberApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MemberApiTests
    {
        private MemberApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MemberApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MemberApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MemberApi
            //Assert.IsInstanceOfType(typeof(MemberApi), instance, "instance is a MemberApi");
        }

        /// <summary>
        /// Test ApiMemberCardPost
        /// </summary>
        [Test]
        public void ApiMemberCardPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RegisterCardRequest body = null;
            //instance.ApiMemberCardPost(body);
            
        }
        /// <summary>
        /// Test ApiMemberGet
        /// </summary>
        [Test]
        public void ApiMemberGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiMemberGet();
            
        }
        /// <summary>
        /// Test ApiMemberIdGet
        /// </summary>
        [Test]
        public void ApiMemberIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.ApiMemberIdGet(id);
            
        }
        /// <summary>
        /// Test ApiMemberPost
        /// </summary>
        [Test]
        public void ApiMemberPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MemberRequest body = null;
            //instance.ApiMemberPost(body);
            
        }
        /// <summary>
        /// Test ApiMemberPut
        /// </summary>
        [Test]
        public void ApiMemberPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MemberRequest body = null;
            //instance.ApiMemberPut(body);
            
        }
    }

}
