/* 
 * WeatherForecast
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserApiTests
    {
        private UserApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserApi
            //Assert.IsInstanceOfType(typeof(UserApi), instance, "instance is a UserApi");
        }

        /// <summary>
        /// Test ApiUserGet
        /// </summary>
        [Test]
        public void ApiUserGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiUserGet();
            
        }
        /// <summary>
        /// Test ApiUserIdGet
        /// </summary>
        [Test]
        public void ApiUserIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.ApiUserIdGet(id);
            
        }
        /// <summary>
        /// Test ApiUserPost
        /// </summary>
        [Test]
        public void ApiUserPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserRequest body = null;
            //instance.ApiUserPost(body);
            
        }
        /// <summary>
        /// Test ApiUserPut
        /// </summary>
        [Test]
        public void ApiUserPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserRequest body = null;
            //instance.ApiUserPut(body);
            
        }
        /// <summary>
        /// Test ApiUserRolesGet
        /// </summary>
        [Test]
        public void ApiUserRolesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiUserRolesGet();
            
        }
    }

}
