/* 
 * WeatherForecast
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HistoryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HistoryRequestTests
    {
        // TODO uncomment below to declare an instance variable for HistoryRequest
        //private HistoryRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HistoryRequest
            //instance = new HistoryRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HistoryRequest
        /// </summary>
        [Test]
        public void HistoryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HistoryRequest
            //Assert.IsInstanceOfType<HistoryRequest> (instance, "variable 'instance' is a HistoryRequest");
        }


        /// <summary>
        /// Test the property 'Activity'
        /// </summary>
        [Test]
        public void ActivityTest()
        {
            // TODO unit test for the property 'Activity'
        }
        /// <summary>
        /// Test the property 'Cardid'
        /// </summary>
        [Test]
        public void CardidTest()
        {
            // TODO unit test for the property 'Cardid'
        }
        /// <summary>
        /// Test the property 'Guest'
        /// </summary>
        [Test]
        public void GuestTest()
        {
            // TODO unit test for the property 'Guest'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

    }

}
